package com.API.Final.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import com.API.Final.Model.Claim;

public interface ClaimRepository extends JpaRepository<Claim, Integer>{
	@Query(value = "SELECT BILLS.id, BILLS.CLAIM_NO,PROVIDER.PROVIDER,BILLS.AMOUNT_PAYABLE,BILLS.INVOICE_NO,BILLS.INVOICE_DATE,BILLS_PAYMENT.CHEQUE_NO,BILLS.MEMBER_NO, SUM(BILLS.INVOICED_AMOUNT) AS INVOICED_AMOUNT  FROM BILLS INNER JOIN BILLS_PAYMENT\r\n"
			+ "ON BILLS.PAYMENT_NO = BILLS_PAYMENT.PAYMENT_NO INNER JOIN PROVIDER ON PROVIDER.CODE=BILLS.PROVIDER  WHERE  BILLS.claim_NO=?1 GROUP BY BILLS.id, BILLS.CLAIM_NO,PROVIDER.PROVIDER,BILLS.AMOUNT_PAYABLE,BILLS.INVOICE_NO,BILLS.INVOICE_DATE,BILLS_PAYMENT.CHEQUE_NO,BILLS.MEMBER_NO ", nativeQuery = true)
	List<Claim> findByClaim_NO(String claim_NO);
	
	@Query(value = "SELECT BILLS.id, BILLS.CLAIM_NO,BILLS.PROVIDER,BILLS.AMOUNT_PAYABLE,BILLS.INVOICE_NO,BILLS.INVOICE_DATE,BILLS_PAYMENT.CHEQUE_NO,BILLS.MEMBER_NO,BILLS.INVOICED_AMOUNT  FROM BILLS INNER JOIN BILLS_PAYMENT\r\n"
			+ "ON BILLS.PAYMENT_NO = BILLS_PAYMENT.PAYMENT_NO  WHERE  BILLS.claim_NO=?1", nativeQuery = true)
	Claim findByClaim(String claim_NO);

}